name: SonarQube Analysis

on:
  push:
    branches:
      - main # Change this to the branch you want to analyze
  pull_request:
    branches:
      - main # Change this to the branch you want to analyze

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarScanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonarqube-${{ runner.os }}

      - name: Run SonarQube Scanner
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_PROJECT_KEY: <your-project-key>
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY \
            -Dsonar.organization=<your-organization-key> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONARQUBE_TOKEN