name: SonarQube Analysis

on:
  push:
    branches:
      - main # Change this to the branch you want to analyze
  pull_request:
    branches:
      - main # Change this to the branch you want to analyze

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SonarScanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonarqube-${{ runner.os }}

      - name: Install SonarScanner
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_PROJECT_KEY: "ivelevi"
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          echo "export PATH=\$PATH:/opt/sonar-scanner/bin" >> $GITHUB_ENV

      - name: Check PATH
        run: echo $PATH

      - name: Run SonarQube Scanner
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_PROJECT_KEY: "ivelevi"
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY \
            -Dsonar.organization="ivelevi" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONARQUBE_TOKEN
