name: ONHOST DEPLOYMENT

on:
  push:
    branches: [ main, dev, staging ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create env
        run: |
          ref="${repo/doc9-whom/doc9cloud}"
          echo $ref
          echo "::set-env name=repository::$ref"
          
          if [[ "$branch" == "dev" ]]
          then
            echo "::set-env name=label::dev"
          elif [ "$branch" == "staging"  ]
          then
            echo "::set-env name=label::staging"
          else
            echo "::set-env name=label::-prod-${{ github.run_number }}"
          fi
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $repository:$label

      - name: Docker Push
        run: echo $repository:$label